version: "3"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4568-4576:4568-4576"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=dynamodb:4569,kinesis:4568
      - AWS_ACCESS_KEY_ID=blah
      - AWS_SECRET_ACCESS_KEY=blah
      - DEFAULT_REGION=ap-southeast-2
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/private${TMPDIR}:/tmp/localstack"
    networks:
      - my_network

  seqLog:
    image: datalust/seq:latest
    ports:
      - "80:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - my_network
      
  setup-resources:
    image: mesosphere/aws-cli
    volumes:
      - ./dev_env:/project/dev_env
    environment:
      - AWS_ACCESS_KEY_ID=blah
      - AWS_SECRET_ACCESS_KEY=blah
      - AWS_DEFAULT_REGION=ap-southeast-2
    entrypoint: /bin/sh -c
    command: >
      "
        # Needed so all localstack components will startup correctly 
        # sleep 10;

        aws dynamodb create-table --endpoint-url=http://localstack:4569 --table-name Development-BlockchainStore \
          --attribute-definitions \
            AttributeName=BlockId,AttributeType=N \
          --key-schema \
            AttributeName=BlockId,KeyType=HASH \
          --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1;
              
        aws kinesis create-stream --endpoint-url=http://localstack:4568 --stream-name Blockchain --shard-count 1;

        aws kinesis create-stream --endpoint-url=http://localstack:4568 --stream-name Transaction --shard-count 1;

      "
    networks:
      - my_network
    depends_on:
      - localstack

networks:
  my_network: